// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

import { appwriteConfig, database } from "~/appwrite/client";


interface Documents {
  [key: string]: any,
}

type DashboardStats = {
  items: Documents[],
  key: string,
  start: string,
  end?: string,
}

type Module = typeof import("../dashboard.js")

type Info = GetInfo<{
  file: "routes/admin/dashboard.tsx",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../../root.js");
}, {
  id: "routes/root/root-layout";
  module: typeof import("../../root/root-layout.js");
}, {
  id: "routes/admin/admin-layout";
  module: typeof import("../admin-layout.js");
}, {
  id: "routes/admin/dashboard";
  module: typeof import("../dashboard.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }, false>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];
}


export const getUsersAndTripsStats = async () => {
  const d = new Date();

  const startCurrent = new Date(d.getFullYear(), d.getMonth(), 1).toISOString();
  const startPrev = new Date(d.getFullYear(), d.getMonth() - 1, 1).toISOString();
  const endPrev = new Date(d.getFullYear(), d.getMonth(), 0).toISOString();

  const [users, trips] = await Promise.all([
    database.listDocuments(
      appwriteConfig.databaseId,
      appwriteConfig.userCollectionId,
    ),
    database.listDocuments(
      appwriteConfig.databaseId,
      appwriteConfig.tripCollectionId,
    )
  ]);

  const filterByDate = ({items, key, start, end}: DashboardStats) => {
    items.filter((item) => (
      item[key] >= start && (!end || item[key] <= end)
    )).length;
  }

  const filterUsersByRole = (role: string) => {
    return users.documents.filter((u) => u.status === role ).length;
  }

  // return {
  //   totalUsers: users.total,
  //   usersJoined: {
  //     thisMonth: filterByDate({ items: users.documents, key: "createdAt", start: startCurrent }),
  //   }
  // }

}