// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/auth-processing": {
    params: {};
  };
  "/api/create-trip": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/all-users": {
    params: {};
  };
  "/trips": {
    params: {};
  };
  "/trips/create": {
    params: {};
  };
  "/trips/:tripId": {
    params: {
      "tripId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/auth-processing" | "/api/create-trip" | "/dashboard" | "/all-users" | "/trips" | "/trips/create" | "/trips/:tripId";
  };
  "routes/root/root-layout.tsx": {
    id: "routes/root/root-layout";
    page: "/" | "/sign-in" | "/auth-processing" | "/api/create-trip" | "/dashboard" | "/all-users" | "/trips" | "/trips/create" | "/trips/:tripId";
  };
  "routes/root/index.tsx": {
    id: "routes/root/index";
    page: "/";
  };
  "routes/root/sign-in.tsx": {
    id: "routes/root/sign-in";
    page: "/sign-in";
  };
  "routes/auth/processing.tsx": {
    id: "routes/auth/processing";
    page: "/auth-processing";
  };
  "routes/api/create-trip.ts": {
    id: "routes/api/create-trip";
    page: "/api/create-trip";
  };
  "routes/admin/admin-layout.tsx": {
    id: "routes/admin/admin-layout";
    page: "/dashboard" | "/all-users" | "/trips" | "/trips/create" | "/trips/:tripId";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/dashboard";
  };
  "routes/admin/all-users.tsx": {
    id: "routes/admin/all-users";
    page: "/all-users";
  };
  "routes/admin/trips.tsx": {
    id: "routes/admin/trips";
    page: "/trips";
  };
  "routes/admin/CreateTrip.tsx": {
    id: "routes/admin/CreateTrip";
    page: "/trips/create";
  };
  "routes/admin/TripDetails.tsx": {
    id: "routes/admin/TripDetails";
    page: "/trips/:tripId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/root/root-layout": typeof import("./app/routes/root/root-layout.tsx");
  "routes/root/index": typeof import("./app/routes/root/index.tsx");
  "routes/root/sign-in": typeof import("./app/routes/root/sign-in.tsx");
  "routes/auth/processing": typeof import("./app/routes/auth/processing.tsx");
  "routes/api/create-trip": typeof import("./app/routes/api/create-trip.ts");
  "routes/admin/admin-layout": typeof import("./app/routes/admin/admin-layout.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/all-users": typeof import("./app/routes/admin/all-users.tsx");
  "routes/admin/trips": typeof import("./app/routes/admin/trips.tsx");
  "routes/admin/CreateTrip": typeof import("./app/routes/admin/CreateTrip.tsx");
  "routes/admin/TripDetails": typeof import("./app/routes/admin/TripDetails.tsx");
};